feat: add template overview and examples
go-vela/docs-old pull request #126
Opened 2020-04-28 14:06 UTC by kneal

2020-04-28 14:11 UTC, meinenec commented on content/templates/overview.md
> +Templates can take the form of generalized workflows across repositories or complex workflows like matrixes in a single build.
`matrices` is the plural form of matrix

2020-04-28 16:47 UTC, meinenec requested changes

2020-04-28 16:47 UTC, meinenec commented on content/templates/overview.md
> +Templates can take the form of generalized workflows across repositories or complex workflows like matrixes in a single build.
`matrices` is the plural form of matrix.

2020-04-28 16:47 UTC, meinenec commented on content/templates/overview.md
> +For, this example we will call it build.yml but the Yaml does not have a required name.
no comma, also I think it's stylized as "YAML"

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/conditional.md
> +We recommend reviewing [Go Templates documentation](https://golang.org/pkg/text/template/) before attempting to create a templates.
`create a template` or `create templates`

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/conditional.md
> + If you're new to Yaml we also recommend reviewing the [Yaml 1.2 spec](https://yaml.org/spec/1.2/spec.html) for validation on syntax.
stylized as YAML

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/conditional.md
> +Lets take a look at using a conditional with a variable in a template:
Let's

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/loops_maps.md
> + If you're new to Yaml we also recommend reviewing the [Yaml 1.2 spec](https://yaml.org/spec/1.2/spec.html) for validation on syntax.
Stylized as `YAML`

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/loops_maps.md
> +Lets take a look at ranging over a map for a template:
should be `Let's`

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/loops_slice.md
> + If you're new to Yaml we also recommend reviewing the [Yaml 1.2 spec](https://yaml.org/spec/1.2/spec.html) for validation on syntax.
stylized as "YAML"

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/loops_slice.md
> +Lets take a look at ranging over a slice for a template:
Let's

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/mulitline.md
> + If you're new to Yaml we also recommend reviewing the [Yaml 1.2 spec](https://yaml.org/spec/1.2/spec.html) for validation on syntax.
YAML

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/mulitline.md
> +```
I'm not sure what this is supposed to be showing me.

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/mulitline.md
> +```
Also not sure what this is showing me. Is there supposed to be a second example showing what this looks like when resolved?

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/mulitline.md
> +From [Yaml Spec Scalars](https://yaml.org/spec/1.2/spec.html):
YAML

2020-04-28 16:47 UTC, meinenec commented on content/templates/tutorials/mulitline.md
> +Lets take a look at using a conditional with a variable in a template:
Let's

2020-04-28 16:47 UTC, KellyMerrick commented on content/templates/tutorials/conditional.md
> +We recommend reviewing [Go Templates documentation](https://golang.org/pkg/text/template/) before attempting to create a templates.
a template, or templates

2020-04-28 16:50 UTC, KellyMerrick commented on content/templates/tutorials/loops_maps.md
> +We recommend reviewing [Go Templates documentation](https://golang.org/pkg/text/template/) before attempting to create a templates.
a template, or templates

2020-04-28 16:51 UTC, KellyMerrick commented on content/templates/tutorials/loops_slice.md
> +We recommend reviewing [Go Templates documentation](https://golang.org/pkg/text/template/) before attempting to create a templates.
a template, or templates

2020-04-28 16:51 UTC, KellyMerrick commented on content/templates/tutorials/mulitline.md
> +We recommend reviewing [Go Templates documentation](https://golang.org/pkg/text/template/) before attempting to create a templates.
a template, or templates

2020-04-28 17:14 UTC, kneal commented on content/templates/tutorials/mulitline.md
> +```
I will try to answer both of what I'm trying to accomplish in these above.

2020-04-28 17:37 UTC, kneal commented on content/templates/tutorials/mulitline.md
> +```
So, admittedly this section I know will be kind of tough to understand and I struggled on formatting or even adding it. What I am trying to accomplish is calling out the specific section I am linking in the YAML spec.

As we all know YAML is very finicky when it comes to indentation, for that reason the syntax you use for multiline strings **needs** to mimic the behavior you're trying to achieve. The best way to understand that is **to read the YAML spec** which I know not everyone will do. So, I pulled out the important sentence in the spec the user needs to care about. Which apparently removed the context of the documentation on scalar syntax.

I personally, had no idea how scalars worked in YAML until I read the entire spec. Which is a commitment but the users writing templates need to understand some of those complex YAML features to achieve what they want with the Go template engine. Otherwise, the outputted pipeline my not fit what they intended

So, let's look at an example with a step using `|` vs `>` for adding a multiline:

_Going to omit the template file in the examples_

---

> `|` - In literals, newlines are preserved
> 
> ```yaml
> --- |
>   \//||\/||
>   // ||  ||__
> ```

**New lines are preserved**
```yaml

# Pipeline using a template passing multiline strings with YAML scalars that keep new lines
steps:
  - name: sample
    template:  
      name: golang
      vars:
        test: |
          - name: test
              commands:
                - go test ./...
              image: golang:latest
              pull: true
              ruleset:
               event: [ push, pull_request ]

# Will produce a result
version: "1"
steps:
  - name: sample_test
    commands:
      - go test ./...
    image: golang:latest
    pull: true
    ruleset:
      event: [ push, pull_request ]

  - name: sample_build
    commands:
      - go build
    image: golang:latest
    pull: true
    ruleset:
      event: [ push, pull_request ]
```
 
So, based on that result we see the YAML indentation is properly aligned and can be compiled on the result **I** the user want

---

> `>` - In the folded scalars, newlines become spaces
> 
> ```yaml
> --- >
>   Mark McGwire's
>   year was crippled
>   by a knee injury.
> ```

**New lines are NOT preserved**
```yaml

# Pipeline using a template passing multiline strings with YAML scalars that DO NOT keep new lines
steps:
  - name: sample
    template:  
      name: golang
      vars:
        test: >
          - name: test
              commands:
                - go test ./...
              image: golang:latest
              pull: true
              ruleset:
               event: [ push, pull_request ]


# Will produce a result
version: "1"
steps:
- name: sample_test
commands:
- go test ./...
image: golang:latest
pull: true
ruleset:
event: [ push, pull_request ]

  - name: sample_build
    commands:
      - go build
    image: golang:latest
    pull: true
    ruleset:
      event: [ push, pull_request ]
```
 
This pipeline will fail the compile process because of how I wrote the template


Sorry, for the very long explanation the TLDR, is that how you write the template and parent pipeline need to combine to make a pipeline that can be compiled. It is totally far to use either method but you need to compensate in the template or parent YAML for the type of multiline string you're using. 

The frustrating part is I'm only calling out the two most common scalars, YAML does have other forms that are valid and produce different results. Which is the pattern I'm using for the Go template syntax. Introduce if conditionals, make them look at the docs for if/else

2020-04-28 17:43 UTC, jbrockopp requested changes
Think it's a great start! Provided a couple items that might be worth reviewing 👍

2020-04-28 17:43 UTC, jbrockopp commented on content/templates/overview.md
> +The following YAML tags are not valid inside a template pipeline:
Perhaps this should be inside an `alert` block with the `warning` label (color)?

This will help that message "stand out" as users are scrolling through.

i.e.

```
{{% alert color="tip" %}}
The following YAML tags are not valid inside a template pipeline:

- `services:`
- `secrets:`
- `stages:`
- `templates:`
{{% /alert %}}

2020-04-28 17:43 UTC, jbrockopp commented on content/templates/tutorials/conditional.md
> + If you're new to YAML we also recommend reviewing the [YAML 1.2 spec](https://yaml.org/spec/1.2/spec.html) for validation on syntax.
think there is an extra space here in front of the `If`

2020-04-28 17:43 UTC, jbrockopp commented on content/templates/tutorials/loops_slice.md
> + If you're new to YAML we also recommend reviewing the [YAML 1.2 spec](https://yaml.org/spec/1.2/spec.html) for validation on syntax.
extra space in front of the `If`

2020-04-28 17:45 UTC, kneal commented on content/templates/overview.md
> +The following YAML tags are not valid inside a template pipeline:
I like that!

2020-04-28 17:49 UTC, kneal commented on content/templates/tutorials/conditional.md
> + If you're new to YAML we also recommend reviewing the [YAML 1.2 spec](https://yaml.org/spec/1.2/spec.html) for validation on syntax.
There is! Good catch!

2020-04-28 17:49 UTC, kneal commented on content/templates/tutorials/loops_slice.md
> + If you're new to YAML we also recommend reviewing the [YAML 1.2 spec](https://yaml.org/spec/1.2/spec.html) for validation on syntax.
There is! Good catch!

2020-04-28 18:39 UTC, meinenec commented on content/templates/tutorials/mulitline.md
> +```
This makes sense however I do not think what we are currently documenting provides value in its current state.

```
From [YAML Spec Scalars](https://yaml.org/spec/1.2/spec.html):

* `|` - In literals, newlines are preserved
> 
> ```yaml
> --- |
>   \//||\/||
>   // ||  ||__
> ```
* `>` - In the folded scalars, newlines become spaces

> ```yaml
> --- >
>   Mark McGwire's
>   year was crippled
>   by a knee injury.
> ```
{{% alert color="tip" %}}
For information on more types of scalars read the [spec information](https://yaml.org/spec/1.2/spec.html#id2760844)
{{% /alert %}}
```

I'm not sure if either of these example mean anything to a user reading this documentation.
An example without a description is kind of useless. The `|` example in particular is arcane and confusing.
After reading the linked documentation further it appears to just be YAML in ASCII art?

What you said was a good explanation, but I think we would agree that it's not our responsibility to document Scalars, and (besides the ASCII example that took me way to long to figure out) the linked docs do a fine job.

We can maybe call out the scalars since we have an example below with `|`?
maybe a table?
| Scalar | Functionality | Example | Becomes |
|-------|--------------|----------|----------|
| \| | Preserves new lines | foo: \| <br>\- test | foo:<br>\- test |
| > | Does not preserve new lines| foo: > <br>\- test | foo: - test |

I think the current iteration adds more confusion than value. I'm not sure the best way to showcase it but I would rather not have anything besides the link than add something that may confuse a user.

2020-04-28 18:44 UTC, kneal commented on content/templates/tutorials/mulitline.md
> +```
Do you feel we should add all the scalars then with that table? Or stay with the two? I think there is six total scalar designs in YAML 1.2.

2020-04-28 19:05 UTC, meinenec commented on content/templates/tutorials/mulitline.md
> +```
I wouldn't be opposed to documenting more. We could also document less and just document `|` since that's the only one we use in the example.

2020-04-28 19:17 UTC, kneal commented on content/templates/tutorials/mulitline.md
> +```
I think I'd rather document less and push people to the Spec docs if need be. I'm nervous about documentation rabbit holes. If you read their docs it should be apparent. 

I'll update this to reflect our conversation.

2020-04-28 19:51 UTC, meinenec commented on content/templates/tutorials/mulitline.md
> +```
I agree with you. Thanks for documenting this!

2020-04-28 20:31 UTC, jbrockopp submitted a review, later dismissed
LGTM

2020-04-29 15:58 UTC, wass3r submitted a review, later dismissed

2020-04-29 16:03 UTC, wass3r commented on content/templates/overview.md
> +At this time the only supported template engine is [Go Templates](https://golang.org/pkg/text/template/). Go templates does allow custom functions to be created and used within the template. We use t
> Go templates does allow custom functions to be created and used within the template.

Nitpicky, bit as a user you won't be able to add any functions, is the callout meant to indicate that we would accept PRs to add functions? Otherewise, I would drop and extend the following sentence with: `We extend Go's built-in template functions with the sprig functions library .. `

2020-04-29 16:44 UTC, kneal commented on content/templates/overview.md
> +At this time the only supported template engine is [Go Templates](https://golang.org/pkg/text/template/). Go templates does allow custom functions to be created and used within the template. We use t
Ummm.... didn't think about that but I think we are probably open to PRs if there is a valid use case.

2020-04-29 16:48 UTC, wass3r commented on content/templates/overview.md
> +At this time the only supported template engine is [Go Templates](https://golang.org/pkg/text/template/). Go templates does allow custom functions to be created and used within the template. We use t
no problem. i can see someone misinterpreting that and thinking they can add functions.. that's the only reason i piped up.

2020-04-29 17:36 UTC, kneal commented on content/templates/overview.md
> +At this time the only supported template engine is [Go Templates](https://golang.org/pkg/text/template/). Go templates does allow custom functions to be created and used within the template. We use t
I can update it, we haven't merged yet. I think your phrasing might sound more appropriate

2020-04-29 20:26 UTC, meinenec submitted a review, later dismissed
Approved. Waiting to merge until the comments from @wass3r are resolved 😄

2020-04-30 13:29 UTC, kneal commented on content/templates/overview.md
> +At this time the only supported template engine is [Go Templates](https://golang.org/pkg/text/template/). Go templates does allow custom functions to be created and used within the template. We use t
@wass3r Updated the phrasing on it 😄

2020-04-30 13:30 UTC, kneal commented
@meinenec @jbrockopp Think everything is sorted out now 😄

2020-04-30 13:37 UTC, jbrockopp submitted a review, later dismissed
LGTM

2020-04-30 14:14 UTC, JordanSussman commented on content/templates/overview.md
> +At this time the only supported template engine is [Go Templates](https://golang.org/pkg/text/template/). We extend Go's built-in template functions to add the [sprig library](http://masterminds.gith
I think this could be clarified with the simple change suggested

```suggestion
At this time the only supported template engine is [Go Templates](https://golang.org/pkg/text/template/). We extend Go's built-in template functions by utilizing the [sprig library](http://masterminds.github.io/sprig/) in the engine to allow for more options on top of the Go template syntax.
```

2020-04-30 14:26 UTC, kneal commented on content/templates/overview.md
> +At this time the only supported template engine is [Go Templates](https://golang.org/pkg/text/template/). We extend Go's built-in template functions to add the [sprig library](http://masterminds.gith
Fixed

2020-04-30 14:28 UTC, wass3r approved these changes

2020-04-30 14:28 UTC, jbrockopp approved these changes
LGTM

2020-04-30 14:30 UTC, merged