refactor(cli): update docs for CLI changes
go-vela/docs-old pull request #143
Opened 2020-07-08 13:54 UTC by jbrockopp

2020-07-10 13:51 UTC, kneal requested changes

2020-07-10 13:51 UTC, kneal commented on content/cli/config/generate.md
> +| `addr`        | full URL to API server              | `VELA_ADDR`, `CONFIG_ADDR`               |
I believe this should be `addr` to `api.addr`

2020-07-10 13:51 UTC, kneal commented on content/cli/config/generate.md
> +| `token`       | user token from API server          | `VELA_TOKEN`, `CONFIG_TOKEN`             |
I believe this should be `token` to `api.token`

2020-07-10 13:51 UTC, kneal commented on content/cli/service/view.md
> +| `service`   | number of the service                | `VELA_SERVICE`, `SERVICE_NUMBER`   |
Think the table formatting might be off here

2020-08-04 15:32 UTC, KellyMerrick approved these changes
lgtm

2020-08-04 18:51 UTC, plyr4 approved these changes

2020-08-04 18:52 UTC, merged