feat: add concept docs for worker routing
go-vela/docs-old pull request #154
Opened 2020-08-07 14:20 UTC by kneal

2020-08-07 15:41 UTC, jbrockopp submitted a review, later dismissed
LGTM

2020-08-10 14:37 UTC, meinenec requested changes

2020-08-10 14:37 UTC, meinenec commented on content/concepts/pipeline/worker/_index.md
> +This declaration allows you to route you build to a subset of workers within a Vela cluster.
>route ~you~ your build

2020-08-10 14:37 UTC, meinenec commented on content/concepts/pipeline/worker/_index.md
> +This pipeline will start and run on a worker with the available queue `docker:large`
This is the only time we use the word `queue` in this PR. Should we change that to `route` to be consistent?

2020-08-10 14:37 UTC, meinenec commented on content/concepts/pipeline/worker/flavor.md
> +The `flavor` component is a part of a [template](/docs/concepts/pipeline/templates/) for Vela.
We don't mention `flavor` in docs page you link. Should we update those docs to show this?
Flavor isn't specific to the templates, right? This sentence makes it seem like it is.

2020-08-10 14:37 UTC, meinenec commented on content/concepts/pipeline/worker/flavor.md
> +  template: false
>The `flavor` component is a part of a [template](/docs/concepts/pipeline/templates/) for Vela.

If this is true, we should use a template example.

2020-08-10 14:37 UTC, meinenec commented on content/concepts/pipeline/worker/platform.md
> +The `platform` component is a part of a [template](/docs/concepts/pipeline/templates/) for Vela.
We don't mention platform in docs page you link. Should we update those docs to show this?
Platform isn't specific to the templates, right? This sentence makes it seem like it is.

2020-08-10 14:45 UTC, kneal commented on content/concepts/pipeline/worker/flavor.md
> +The `flavor` component is a part of a [template](/docs/concepts/pipeline/templates/) for Vela.
Just a copy/paste error. Will fix

2020-08-10 14:45 UTC, kneal commented on content/concepts/pipeline/worker/flavor.md
> +  template: false
Just a copy/paste error. Will fix

2020-08-10 14:45 UTC, kneal commented on content/concepts/pipeline/worker/platform.md
> +The `platform` component is a part of a [template](/docs/concepts/pipeline/templates/) for Vela.
Just a copy/paste error. Will fix

2020-08-10 14:56 UTC, kneal commented
@meinenec should be fixed

2020-08-10 15:19 UTC, meinenec approved these changes

2020-08-10 16:46 UTC, wass3r approved these changes

2020-08-10 16:46 UTC, merged