feat(schema): add schema information
go-vela/docs-old pull request #163
Opened 2020-08-25 18:33 UTC by wass3r

2020-08-26 12:53 UTC, jbrockopp requested changes

2020-08-26 12:53 UTC, jbrockopp commented on content/usage/validation/_index.md
> +Integration with editors can enhance your pipeline writing experience by providing autocompletion, inline documentation, and links to documention within your editor.
```suggestion
Integration with editors can enhance your pipeline writing experience by providing autocompletion, inline documentation, and links to documentation within your editor.
```

2020-08-26 15:21 UTC, jbrockopp submitted a review, later dismissed
LGTM

2020-08-27 13:30 UTC, jbrockopp approved these changes
LGTM

2020-08-27 13:35 UTC, KellyMerrick approved these changes
lgtm

2020-08-27 13:35 UTC, merged