enhancement: update how to build docker images
go-vela/docs-old pull request #174
Opened 2020-10-05 15:54 UTC by kneal

The changes make the following plugin docs changes:

* Removed content from Docker, and point to Kaniko
* Added new section for Kaniko docs
* Added new section for Makisu docs

2020-10-06 16:39 UTC, jbrockopp requested changes

2020-10-06 16:39 UTC, jbrockopp commented on content/plugins/pipeline/registry/kaniko.md
> +This plugin uses [Kaniko](https://github.com/GoogleContainerTools/kaniko) to provide the ability to build and publish [Docker](https://www.docker.com/) images in a Vela pipeline without evaluated acc
```suggestion
This plugin uses [Kaniko](https://github.com/GoogleContainerTools/kaniko) to provide the ability to build and publish [Docker](https://www.docker.com/) images in a Vela pipeline without elevated access on the workers.
```

2020-10-06 16:39 UTC, jbrockopp commented on content/plugins/pipeline/registry/makisu.md
> +This plugin uses [Kaniko](https://github.com/uber/makisu) to provide the ability to build and publish [Docker](https://www.docker.com/) images in a Vela pipeline without evaluated access on the worke
```suggestion
This plugin uses [Kaniko](https://github.com/uber/makisu) to provide the ability to build and publish [Docker](https://www.docker.com/) images in a Vela pipeline without elevated access on the workers.
```

2020-10-06 16:39 UTC, jbrockopp commented on content/usage/getting-started/docker.md
> +Both options have disadvantages and advantages, so we encourage all Vela administrators to way the pros/cons of how they want to build Docker images for their cluster.
```suggestion
Both options have disadvantages and advantages, so we encourage all Vela administrators to weigh the pros/cons of how they want to build Docker images for their cluster.
```

2020-10-06 18:28 UTC, jbrockopp submitted a review, later dismissed
LGTM

2020-10-07 15:43 UTC, wass3r commented on content/plugins/pipeline/registry/docker.md
> +This plugin was originally used to build **all** Docker images. The functionality of this plugin still exists within [Kaniko](/kaniko)
is that the right link to kaniko?

2020-10-07 15:43 UTC, wass3r commented on content/plugins/pipeline/registry/makisu.md
> +Below are a list of common problems and how to solve them:
change to "COMING SOON!"?

2020-10-07 16:13 UTC, kneal commented on content/plugins/pipeline/registry/docker.md
> +This plugin was originally used to build **all** Docker images. The functionality of this plugin still exists within [Kaniko](/kaniko)
I think that relative link will work but I can do the full link to be safe

2020-10-08 14:48 UTC, wass3r commented on content/plugins/pipeline/registry/docker.md
> +This plugin was originally used to build **all** Docker images. The functionality of this plugin still exists within [Kaniko](/kaniko)
yea, i don't think that will work.. i think that will reference https://go-vela.github.io/kaniko?

2020-10-08 17:22 UTC, jbrockopp approved these changes
LGTM

2020-10-08 17:24 UTC, wass3r approved these changes

2020-10-08 17:24 UTC, merged