feat: add docker pluigin docs
go-vela/docs-old pull request #177
Opened 2020-10-20 14:29 UTC by kneal

2020-10-20 20:41 UTC, jbrockopp requested changes

2020-10-20 20:41 UTC, jbrockopp commented on content/plugins/pipeline/registry/docker.md
> +| `mtu`                 | enable setting the containers network MTU               | `false`  | N/A     |
I noticed we use both `enable ...` and `enables ...` for the parameter descriptions.

Should we update it one way or the other to be consistent?

2020-10-23 15:45 UTC, jbrockopp approved these changes
LGTM

2020-10-23 20:47 UTC, wass3r approved these changes

2020-10-23 20:48 UTC, merged