feat(templates): add starlark documentation
go-vela/docs-old pull request #185
Opened 2020-11-13 14:36 UTC by kneal

2020-11-13 15:08 UTC, JordanSussman commented on content/templates/tutorials/starlark/_index.md
> +
Probably worthwhile to provide some extra explanation that we convert `VELA_REPO_FULL_NAME` into `ctx["vela"]["repo"]["full_name"]`. May also be helpful if the link to the page(s) that document the available environment variables.

2020-11-13 15:12 UTC, JordanSussman commented on content/templates/tutorials/starlark/vars_platform.md
> +            step(ctx["vela"]["repo"]["full_name"]),
We should probably update this to utilize some variable that does not contain a `/` since we know that will break execution if utilized within the step `name`.

2020-11-13 15:13 UTC, JordanSussman commented on content/templates/tutorials/starlark/vars_template.md
> +          test: "go test ./..."
Should we add some note about `maps` not always returning the same order if you loop over them?

2020-12-14 04:14 UTC, meinenec commented on content/templates/_index.md
> +[Starlark](https://github.com/bazelbuild/starlark) is a configuration language that was designed for the [Bazel build system](https://bazel.build/). The language is a [Python](https://www.python.org/
I think this should say "language-esque"

2020-12-28 15:11 UTC, kneal commented on content/templates/_index.md
> +[Starlark](https://github.com/bazelbuild/starlark) is a configuration language that was designed for the [Bazel build system](https://bazel.build/). The language is a [Python](https://www.python.org/
In which part?

2020-12-28 15:55 UTC, JordanSussman commented
@kneal - can you update the golang portion to include references to the `vela` function that was added within https://github.com/go-vela/compiler/pull/92?

2021-01-25 15:45 UTC, meinenec commented on content/templates/_index.md
> +[Starlark](https://github.com/bazelbuild/starlark) is a configuration language that was designed for the [Bazel build system](https://bazel.build/). The language is a [Python](https://www.python.org/
The part that says "language Esque"

2021-01-25 15:51 UTC, wass3r requested changes

2021-01-25 15:51 UTC, wass3r commented on content/templates/_index.md
> +The `format:` option was written backwards compatible. This means by default templates go through it's expansion process. That makes the following options valid Yaml syntax:
```suggestion
The `format:` option was written to be backwards compatible. This means by default templates go through it's expansion process. That makes the following options valid YAML syntax:
```

2021-01-25 15:51 UTC, wass3r commented on content/templates/tutorials/starlark/_index.md
> +### Decision one: all templates must contain a main that returns a pipeline
```suggestion
### Decision one: all templates must contain a "main" function that returns a pipeline
```

2021-01-28 18:33 UTC, closed without merging