refactor(sdk): update available sdk clients
go-vela/docs-old pull request #195
Opened 2021-01-13 18:06 UTC by kneal

This PR will simplify the available documentation on the documentation site. The documentation site is not the source of truth for this documentation and tends to be out of date. This new style will provide where to get the docs along with a simple example.

Content changes:

* Removed Go sdk docs in favor of Godoc
* Adding Go sdk Splash page
* Added Python sdk splash page

2021-01-13 19:14 UTC, matt-fevold submitted a review, later dismissed

2021-01-13 19:19 UTC, jbrockopp requested changes

2021-01-13 19:19 UTC, jbrockopp commented on content/reference/sdk/go.md
> +	"github.com/go-vela/sdk-go/vela"
Super nit-picky but could we fix the spacing here?

2021-01-13 19:19 UTC, jbrockopp commented on content/reference/sdk/go.md
> +	refreshToken := "someRefreshToken"
Could we fix the spacing here?

2021-01-13 19:19 UTC, jbrockopp commented on content/reference/sdk/go.md
> +    }
spacing here?

The comment and code don't match

2021-01-13 19:19 UTC, jbrockopp commented on content/reference/sdk/go.md
> +    client.Authentication.SetAccessAndRefreshAuth(accessToken, refreshToken)
spacing here?

The comment and code don't match

2021-01-13 19:29 UTC, kneal commented on content/reference/sdk/go.md
> +	"github.com/go-vela/sdk-go/vela"
Think we got it!

2021-01-13 19:29 UTC, kneal commented on content/reference/sdk/go.md
> +	refreshToken := "someRefreshToken"
Think we got it!

2021-01-13 19:29 UTC, kneal commented on content/reference/sdk/go.md
> +    }
Think we got it!

2021-01-13 19:29 UTC, kneal commented on content/reference/sdk/go.md
> +    client.Authentication.SetAccessAndRefreshAuth(accessToken, refreshToken)
Think we got it!

2021-01-13 19:33 UTC, jbrockopp approved these changes
LGTM 🎉

2021-01-14 18:32 UTC, matt-fevold approved these changes

2021-01-14 18:57 UTC, merged