feat(ref): add a yaml section
go-vela/docs-old pull request #196
Opened 2021-01-14 20:21 UTC by kneal

This PR adds a new document to the YAML spec. The purpose of this section is to display and explain each tag that can be used in the YAML. The section is **intentionally** written to not be fully qualified pipelines. If users need that they should be looking at the guides/examples provided in the Usage (to be renamed Guides) tab.

The way it is written there will be some duplicate content between concepts and the new ref section. The concepts section is going to be re-imagined in a new branch coming soon. This ref section was inspired by other CI tools documentation for detailing available tags in a YAML spec. 

Inspiration:
https://docs.drone.io/yaml/docker/
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
https://circleci.com/docs/2.0/configuration-reference/#section=reference

This change will require all the YAML spec docs to point to the ref for their YAML tag. 
https://github.com/go-vela/types/blob/master/yaml/build.go#L15-L24

I will make that PR once this is merged and new links are available.

2021-01-15 21:31 UTC, KellyMerrick requested changes

2021-01-15 21:31 UTC, KellyMerrick commented on content/reference/yaml/_index.md
> +Steps and Stages Pipeline use "YAML Ain’t Markup Language" (YAML) which is a data serialization language designed to be human friendly. Vela accepts YAML fles with either a `.yml` or `.yaml` extensio
If you'd like to learn more about the YAML language we recommend you see

2021-01-15 21:31 UTC, KellyMerrick commented on content/reference/yaml/secrets.md
> +plugins to write the external secrets to the build volume.
do we want this on a separate line than the one above?

2021-01-15 21:31 UTC, KellyMerrick commented on content/reference/yaml/services.md
> +# to run a postgre database for the duration of a pipeline.
to run a postgres database for the duration of a pipeline.

2021-01-19 16:55 UTC, kneal commented on content/reference/yaml/secrets.md
> +plugins to write the external secrets to the build volume.
Yeah, the pattern is to have a little intro for each section

2021-01-20 15:36 UTC, KellyMerrick commented on content/reference/yaml/secrets.md
> +plugins to write the external secrets to the build volume.
i meant lines 9 and 10 being on separate lines, instead of a single line. i could have made that clearer. not sure if there was a purpose to the break.

2021-01-28 17:44 UTC, davidvader requested changes
I love it, I approve of the content, just some readability things I would change, but not necessary. Nice work!

2021-01-28 17:44 UTC, davidvader commented on content/reference/yaml/_index.md
> +Whether you are a YAML expert or a novice here is some quick terminology that is used without the Vela reference documentation you should be aware of:
This sentence is a bit of a run-on. Perhaps omit the Vela reference? Im not sure what you mean by "without the Vela reference documentation". Or clarify that part?
 
```suggestion
Whether you are a YAML expert or a novice, here is some quick terminology that you should be aware of:
```

2021-01-28 17:44 UTC, davidvader commented on content/reference/yaml/secrets.md
> +    key: go-vela/foo`
Typo in this secret key?
```suggestion
    key: go-vela/foo2
```

2021-01-28 17:44 UTC, davidvader commented on content/reference/yaml/secrets.md
> +    key: go-vela/admins/foo
Not necessary, but for clarity. Unless the re-use of the same key was intentional, then feel free to ignore this
```suggestion
    key: go-vela/admins/foo3
```

2021-01-28 17:44 UTC, davidvader commented on content/reference/yaml/secrets.md
> +    # can pull repo but tag accepts the
Definitely nit-picky but it might read easier if the sentence starts on the next line 
```suggestion
    # Type of secret to fetch from storage backend.
    #  By default, Vela can pull repo but tag accepts the 
```

2021-01-28 17:44 UTC, davidvader commented on content/reference/yaml/secrets.md
> +In an effort to not duplicate how documentation, to see how tags can be set, see the comparable [step tags documentation](/docs/reference/yaml/steps/#tags) to get behavior details.
More nit-pickiness, the content looks great 👍 
```suggestion
In an effort to reduce duplicate documentation, see the comparable [step tags documentation](/docs/reference/yaml/steps/#tags) to learn how tags can be set and details on behavior.
```

2021-01-28 17:44 UTC, davidvader commented on content/reference/yaml/services.md
> +The services tag is intended to be used to run applications alongside the pipeline.
Following the emphasis pattern used for the previous important tags
```suggestion
The `services` tag is intended to be used to run applications alongside the pipeline.
```

2021-01-28 17:44 UTC, davidvader commented on content/reference/yaml/stages.md
> +The stages tag is intended to be used to one to many sets of steps tasks in parallel.
This sentence reads weird to me

Not in love with my suggestion either 🤷 
```suggestion
The stages tag is intended to be used to parallelize one-to-many sets of step tasks.
```

2021-01-28 17:44 UTC, davidvader commented on content/reference/yaml/stages.md
> +To see how all steps tags, see the [step tags documentation](/docs/reference/yaml/steps/#tags)
Reads weird to me
```suggestion
For more details on all steps tags, see the [step tags documentation](/docs/reference/yaml/steps/#tags)
```

2021-01-28 17:44 UTC, davidvader commented on content/reference/yaml/templates.md
> +The template tag is intended to be used to identity where to retrieve templates during the compiler phase of the pipeline.
typo
```suggestion
The template tag is intended to be used to identify where to retrieve templates during the compiler phase of the pipeline.
```

2021-01-28 17:44 UTC, davidvader commented on content/reference/yaml/version.md
> +The version tag is intended to be used in order to issue warnings for deprecation or breaking changes within the YAML document.
```suggestion
The version tag is intended to be used in order to issue warnings for deprecated features or breaking changes within the YAML document.
```

2021-01-28 17:49 UTC, matt-fevold commented on content/reference/yaml/metadata.md
> +| `clone`    | N        | bool | Enables injecting the default clone process.  |
would having the default value here help?

2021-01-28 17:49 UTC, matt-fevold commented on content/reference/yaml/secrets.md
> +plugins to write the external secrets to the build volume.
+1 to the having it be on the same line and letting the browser word-wrap.

2021-01-28 17:54 UTC, kneal commented on content/reference/yaml/secrets.md
> +    key: go-vela/foo`
yeah, but honestly I should probably have an example showing you can alias as well.

2021-01-28 17:59 UTC, kneal commented on content/reference/yaml/metadata.md
> +| `clone`    | N        | bool | Enables injecting the default clone process.  |
I was wondering about that but a majority of keys don't have default values. So, we could implement it on tables that do and leave the column off on ones that don't or keep it consistent and not add them here

2021-01-29 16:01 UTC, matt-fevold commented on content/reference/yaml/metadata.md
> +| `clone`    | N        | bool | Enables injecting the default clone process.  |
maybe rather than a column, it's just a note within the description (default: true) for the few cases of it.

2021-01-29 16:07 UTC, matt-fevold commented
dismissing the reviews since it appears the feedback was addressed.

2021-01-29 21:52 UTC, jbrockopp commented on content/reference/yaml/templates.md
> +The template tag is intended to be used to identity where to retrieve templates during the compiler phase of the pipeline.
I think I'm still seeing this as `identity` instead of `identify`

2021-01-29 21:53 UTC, jbrockopp commented on content/reference/yaml/version.md
> +The version tag is intended to be used in order to issue warnings for deprecation or breaking changes within the YAML document.
I'm still seeing this as `deprecation` instead of `deprecated features`

2021-01-29 21:53 UTC, jbrockopp commented on content/reference/yaml/secrets.md
> +plugins to write the external secrets to the build volume.
I'm still seeing this as two separate lines

2021-02-01 15:23 UTC, JordanSussman commented on content/reference/yaml/worker.md
> +metadata:
Is this meant to be `worker` instead of `metadata`?

2021-02-01 15:26 UTC, kneal commented on content/reference/yaml/worker.md
> +metadata:
yep!

2021-02-01 15:31 UTC, JordanSussman commented on content/reference/yaml/steps.md
> +#### The `detach:` tag
Presume this was meant to be privileged instead

```suggestion
#### The `privileged:` tag
```

2021-02-01 15:55 UTC, davidvader approved these changes

2021-02-01 16:00 UTC, matt-fevold approved these changes
LGTM 🐕

2021-02-01 16:00 UTC, wass3r approved these changes

2021-02-01 16:05 UTC, matt-fevold commented on content/reference/yaml/secrets.md
> +plugins to write the external secrets to the build volume.
weird UI thing. this has been done

2021-02-01 16:16 UTC, jbrockopp approved these changes
LGTM

2021-02-01 16:36 UTC, KellyMerrick approved these changes
lgtm

2021-02-01 16:38 UTC, merged