Templates
go-vela/docs-old pull request #201
Opened 2021-01-24 01:36 UTC by JordanSussman

supersede #185

2021-01-25 15:47 UTC, davidvader requested changes

2021-01-25 15:47 UTC, davidvader commented on content/templates/tutorials/go/vars_platform.md
> +- `{{ vela "VELA_FULL_REPO_NAME" }}` equates to the `VELA_REPO_NAME` environment variable
should `VELA_REPO_NAME ` be `VELA_FULL_REPO_NAME`
```suggestion
- `{{ vela "VELA_FULL_REPO_NAME" }}` equates to the `VELA_FULL_REPO_NAME` environment variable
```

2021-01-25 16:11 UTC, JordanSussman commented on content/templates/tutorials/go/vars_platform.md
> +- `{{ vela "VELA_FULL_REPO_NAME" }}` equates to the `VELA_REPO_NAME` environment variable
You are correct.

2021-01-28 18:33 UTC, kneal approved these changes
LGTM 🐬

2021-01-28 18:33 UTC, kneal commented
@JordanSussman Will close the draft

2021-01-28 19:49 UTC, jbrockopp approved these changes
LGTM

2021-01-28 19:56 UTC, plyr4 approved these changes

2021-01-28 19:57 UTC, merged