refactor: replace concepts with tour
go-vela/docs-old pull request #207
Opened 2021-02-05 17:07 UTC by kneal

This documentation includes the phrasing and examples from the old [concepts](https://go-vela.github.io/docs/concepts/) but creates a new format called Tour.

The new design is inspired by language Tours. I had a hard time finding comparable docs on other CIs. So, I went with a more unique story driving style format that you can in [Go By Example](https://gobyexample.com/), [Tour of Go](https://tour.golang.org/welcome/1), and [Tour of Rust](https://tourofrust.com/).

2021-02-15 22:29 UTC, matt-fevold reviewed
I didn't get through the whole doco yet, but plan to review more tomorrow. In the meantime here's a few comments to begin a discussion :)

2021-02-15 22:29 UTC, matt-fevold commented on content/tour/_index.md
> +Vela pipelines execute pipeline commands inside ephemeral Docker containers. Docker containers provide isolation, allowing safe execution of concurrent pipelines on the same machine.
I'm sus about this paragraph, but also not sure what to suggest exactly other than it uses a lot of descriptor words that could be confusing. 

> Vela pipelines execute commands inside Docker containers. Because these containers are ephemeral and isolated, it is safe to execute multiple pipelines on the same machine concurrently. 

^ a crack I took at it.

2021-02-15 22:29 UTC, matt-fevold commented on content/tour/_index.md
> +Vela has two core pipeline types steps, and stages. Steps pipelines should be used for use cases when everything in the build workflow need to be done sequentially. Stages are pipelines that are desi
> Vela has two core pipeline types: steps and stages. 

Small grammatical improvement.

I also wonder if making the description of each a bullet point underneath it would be better or if it'd break the "immersion" of the narrative tour.

2021-02-15 22:29 UTC, matt-fevold commented on content/tour/image.md
> +The default behavior is for a Vela worker component to pull an image if not present. Since the Docker daemon builds up a large cache this had the advantage of executing the build very quickly.
> The default behavior for a Vela worker is to pull an image if it's not present [in the cache?]. Since the Docker daemon builds up a large cache, this has the advantage of executing builds much quicker than if they had to download the image every time. 

thoughts on updating this paragraph to this?

2021-02-16 18:21 UTC, matt-fevold requested changes
very cool overall :) just some small wording changes. Dismiss any that don't make sense.

2021-02-16 18:21 UTC, matt-fevold commented on content/tour/plugins.md
> +Anyone can create a plugin and use it in their pipeline.
Do we have customer documentation for creating their own plugins/is it worth linking here?

2021-02-16 18:21 UTC, matt-fevold commented on content/tour/rulesets.md
> +The ruleset allows you to provide conditions to limit the execution of the container.
`A ruleset` or `The ruleset tag`

2021-02-16 18:21 UTC, matt-fevold commented on content/tour/rulesets.md
> +Within that payload contains characteristics about what just happened. Maybe it was a push to the main branch.
`Maybe it was a push to your main branch. `

2021-02-16 18:21 UTC, matt-fevold commented on content/tour/services.md
> +This declaration allows you to provide detached (headless) container for the duration of a pipeline.
This declaration allows you to provide `a` detached (headless) container for the duration of `your` pipeline.

2021-02-16 18:21 UTC, matt-fevold commented on content/tour/services.md
> +Services are always ran, in parallel alongside the ephemeral steps in the pipeline. They are extremely useful when your testing requires additional services such as a cache, database or queue.
> Services are always ran, in parallel, alongside the ephemeral steps in the pipeline.

added comma

2021-02-16 18:21 UTC, matt-fevold commented on content/tour/services.md
> +Services are always created at the beginning of a pipeline in the order they are defined.
> Services are created at the beginning of a pipeline in the order they are defined.

removed `always` - think it reads better

2021-02-16 18:21 UTC, matt-fevold commented on content/tour/services.md
> +The `name:` field of the service defines at what hostname the service will be available.
I like this, but it shouldn't break a part the paragraph above and below.

2021-02-17 15:28 UTC, wass3r commented
i know this PR will break various links (many in `/usage`) in this repo and a bunch of other repos, `types` and `ui` to name a few. can we make sure to create either stories or additional PRs in those to avoid missing those changes?

2021-02-25 15:23 UTC, kneal commented
@wass3r Yeah can definitely take a step back on this since it's such a large change. Converting back to draft for now until I can find time to dedicated to properly updating all the downstream effects. Probably just gonna let this sit for awhile. Thanks for the feedback!

2021-05-27 15:53 UTC, matt-fevold commented on content/tour/_index.md
> +Vela has a few core pipeline types known as steps, stages, and templates. Steps pipelines should be used in situations when everything in the workflow needs to be accomplished sequentially. Stages ar
I may be wrong in my terminology, but aren't matrix builds spread out across multiple workers? Or it's probably more correct to say that you can setup matrix builds to run on multiple workers.

2021-05-27 15:59 UTC, kneal commented on content/tour/_index.md
> +Vela has a few core pipeline types known as steps, stages, and templates. Steps pipelines should be used in situations when everything in the workflow needs to be accomplished sequentially. Stages ar
It's very open to interpretation if you look at CI providers (Actions, Circle, Drone, Concourse, etc) holistically. So, depending on which CI provider a consumer is using they may have an existing interpretation of how that works but it might not be accurate to the one they are looking at. 

The core of the functionality is you have a set of tasks to be run and you can provide input to modify variations of how those tasks run.

2021-05-27 16:04 UTC, matt-fevold commented on content/tour/environment.md
> +With this substitution you should be aware `${variable}` expressions are subject to pre-processing. If you want to avoid this behavior you can escape your expressions to avoid the pre-processor evalu
Can you add an example of this? I skimmed the usage docs linked, but couldn't find an example of escaping `${variable}` - unless that exists somewhere else and could be linked?

2021-05-27 16:07 UTC, kneal commented on content/tour/environment.md
> +With this substitution you should be aware `${variable}` expressions are subject to pre-processing. If you want to avoid this behavior you can escape your expressions to avoid the pre-processor evalu
So, there is an example on that page of the substitution being used with the `0:8` syntax in I believe the build commit env var. 

Additionally, we have new reference docs that [outline substitution expressions](https://go-vela.github.io/docs/reference/environment/substitution/) and how to avoid pre-processing. Those docs are also linked on this tour page.

2021-05-27 16:11 UTC, matt-fevold commented on content/tour/environment.md
> +With this substitution you should be aware `${variable}` expressions are subject to pre-processing. If you want to avoid this behavior you can escape your expressions to avoid the pre-processor evalu
Oh perfect.

2021-05-27 16:48 UTC, kneal commented on content/tour/environment.md
> +With this substitution you should be aware `${variable}` expressions are subject to pre-processing. If you want to avoid this behavior you can escape your expressions to avoid the pre-processor evalu
Definitely open to making that more clear in the tour. I kinda have this back and fourth thing going between like the prompt and the examples and I'm unsure how much content to put on each side

2021-05-27 19:18 UTC, matt-fevold approved these changes, later dismissed
I think for MVP this looks good! A few small non required changes I commented on.

2021-05-27 19:18 UTC, matt-fevold commented on content/tour/secrets.md
> +They are answer when you don’t want to provide that sensitive information in plain text.
> They are answer

They are *the* answer

2021-05-27 19:18 UTC, matt-fevold commented on content/tour/secrets.md
> +    # where source is the name and target is the name of the env var.
source is the *new* name - recommendation

2021-06-01 14:08 UTC, jbrockopp requested changes

2021-06-01 14:08 UTC, jbrockopp commented on content/tour/cloning.md
> +# Below is displaying the turning off the clone behavior that.
Maybe we should remove the trailing `that`?

Also, I wonder if we should adjust the wording slightly here?

```suggestion
# Below is displaying how to turn off the clone behavior. 
```

2021-06-01 14:08 UTC, jbrockopp commented on content/tour/cloning.md
> +  # Now that the turn is cloned off; you can use any Docker
Perhaps we update the wording here?

```suggestion
  # Now that the clone is turned off; you can use any Docker
```

2021-06-01 14:08 UTC, jbrockopp commented on content/tour/environment.md
> +Vela does import a library to provide partial string operations. You can be use the functions to manipulate string values prior to substitution.
Maybe we drop the `be` here?

```suggestion
Vela does import a library to provide partial string operations. You can use the functions to manipulate string values prior to substitution.
```

2021-06-01 14:08 UTC, jbrockopp commented on content/tour/plugins.md
> +        - v1.0.0
Thoughts on adding `PARAMETER_USERNAME` and `PARAMETER_PASSWORD` to the comments?

```suggestion
    # Environment variables injected:
    # PARAMETER_REGISTRY=index.docker.io
    # PARAMETER_REPO=index.docker.io/go-vela/hello-world
    # PARAMETER_USERNAME=moby
    # PARAMETER_PASSWORD=mypassword
    # PARAMETER_TAGS=latest,v1.0.0
    parameters:
      registry: index.docker.io
      repo: index.docker.io/go-vela/hello-world
      username: moby
      password: mypassword
      tags:
        - latest
        - v1.0.0
```

2021-06-01 14:08 UTC, jbrockopp commented on content/tour/services.md
> +However, there are times when you need more control over when a service is created. Perhaps you are dealing with a service that has start up dependencies and service A needs some to to start up befor
I think there is an extra `to` here?

Also I wonder if we should say `something` instead of `some`?

```suggestion
However, there are times when you need more control over when a service is created. Perhaps you are dealing with a service that has start up dependencies and service A needs something to start up before service B is started
```

2021-06-01 14:08 UTC, jbrockopp commented on content/tour/templates.md
> +Templates can solve duplicative tasks in a single workflow or be leveraged any number of pipelines to make reusable tasks across multiple workflows.
Perhaps we add a `by` here?

```suggestion
Templates can solve duplicative tasks in a single workflow or be leveraged by any number of pipelines to make reusable tasks across multiple workflows.
```

2021-06-01 18:17 UTC, jbrockopp submitted a review, later dismissed
LGTM

2021-06-02 15:59 UTC, matt-fevold approved these changes, later dismissed

2021-06-03 16:57 UTC, merged