feat: add environment tag for global injection
go-vela/docs-old pull request #235
Opened 2021-06-21 20:07 UTC by kneal

PR Includes the following changes:

- adds new global environment example to usage
- adds new global environment setting on pipeline
- adds new global environment control setting on metadata

_Story for additionally context https://github.com/go-vela/community/issues/304_

2021-07-13 21:17 UTC, meinenec requested changes
Please correct me on any where I might be wrong!

2021-07-13 21:17 UTC, meinenec commented on content/reference/yaml/metadata.md
> +  # but if block exists configuration specified is used during
for this phrase
> but if block exists configuration specified is used during environment injection during compile phase

I think the way the line is split made this read funny in my head. It might help to say something like

> but if the environment tag exists the specified configuration is used...

2021-07-13 21:17 UTC, meinenec commented on content/usage/environment.md
> +Vela provides the ability to define environment variables scoped to individual steps, services and secrets. Additionally, if you need global environment setting you can set it at the parent and have
again, this might just be how I'm reading it but maybe
> if you need global environment setting

to one of these?

> if you need a global environment setting
> if you need global environment settings
> if you need global environment variables

2021-07-13 21:17 UTC, meinenec commented on content/usage/environment.md
> +Please note the environment is design to be unique per container. Vela does inject a variety of default values from build, repo and user information.
>environment is design

to 

>environment is designed

2021-07-13 21:17 UTC, meinenec commented on content/usage/environment.md
> ++ environment:
should this be under `metadata:`?

2021-07-13 21:17 UTC, meinenec commented on content/usage/environment.md
> +By default global injection effects all containers ran within the pipeline but if only want some container types to receive the configuration you can limit which types get them by adding the `environ
>effects all containers ran within the pipeline but if only want some container types to receive the configuration

I think we're missing a word or two. Maybe two sentences?

>effects all containers ran within the pipeline. If you only want certain container types to receive the configuration

2021-07-13 21:17 UTC, meinenec commented on content/usage/environment.md
> +      # you can use bash commands in-line to set or override variables
super nit-picky but we might want to avoid saying `bash` since I think depends on the default shell of the container.

2021-07-13 21:17 UTC, meinenec commented on content/usage/environment.md
> +  # Global configuration is no longer available in secrets
Was it ever? If it's not supported we can just say so 😄

2021-08-04 16:23 UTC, kneal commented on content/usage/environment.md
> ++ environment:
No, because it's the parent block.

2021-08-04 16:31 UTC, kneal commented
@meinenec Thanks for the feedback, this one is finally ready for re-review. Closed the relevant conversation items.

2021-08-05 12:55 UTC, wass3r approved these changes

2021-08-09 14:03 UTC, meinenec approved these changes

2021-08-09 14:07 UTC, merged