Add link to templates YAML reference documentation
go-vela/docs-old pull request #238
Opened 2021-06-28 15:56 UTC by JohnCgp

Make the reference documentation more discoverable to
people searching for information about Vela templates.

On the heels of #237

2021-07-15 21:36 UTC, wass3r requested changes

2021-07-15 21:36 UTC, wass3r commented on content/templates/_index.md
> +Check out the [YAML reference documentation](https://go-vela.github.io/docs/reference/yaml/templates/) for templates.
```suggestion
Check out the [YAML reference documentation](/docs/reference/yaml/templates/) for templates.
```
I would change to make it a relative link. One benefit is you can test it locally without having links jumps from local to external and potentially get different versions.

2021-07-16 07:56 UTC, JohnCgp commented on content/templates/_index.md
> +Check out the [YAML reference documentation](https://go-vela.github.io/docs/reference/yaml/templates/) for templates.
Good point, done.

2021-07-16 14:00 UTC, wass3r approved these changes

2021-07-16 14:05 UTC, wass3r commented
Thanks for the contribution 🙇🏼

2021-07-16 19:32 UTC, jbrockopp approved these changes
LGTM

2021-07-16 19:32 UTC, merged