chore: add service ulimit docs
go-vela/docs-old pull request #239
Opened 2021-07-21 19:48 UTC by meinenec

adds docs for https://github.com/go-vela/types/pull/190

2021-07-22 16:42 UTC, jbrockopp approved these changes, later dismissed
LGTM

2021-07-22 17:38 UTC, wass3r commented on content/reference/yaml/services.md
> +| `ulimits`     | N        | string          | Set the user limits for the container.                          |
i think this is `[]string` or `[]Ulimit` (though not sure how to depict "Ulimit" here), right?

ref: https://github.com/go-vela/types/blob/v0.8.2/yaml/ulimit.go#L51

2021-07-27 16:46 UTC, wass3r commented on content/reference/yaml/services.md
> +| `ulimits`     | N        | string          | Set the user limits for the container.                          |
probably throw something similar to `environment` in there.. `[]map || []string`?

2021-07-27 16:47 UTC, wass3r requested changes
see comment

2021-07-29 14:23 UTC, meinenec commented on content/reference/yaml/services.md
> +| `ulimits`     | N        | string          | Set the user limits for the container.                          |
ahh I think you're right, I'll update that and make a separate PR for steps (where I copied that from)
https://github.com/go-vela/docs/blob/master/content/reference/yaml/steps.md#tags

Looks like there's a couple fields that can be fixed in steps.

2021-07-30 15:54 UTC, meinenec commented on content/reference/yaml/services.md
> +| `ulimits`     | N        | string          | Set the user limits for the container.                          |
I thought about this a little and don't think `[]map` is valid, but `[]string` and `[]Ulimit` are.
Looking at how we document the [steps array for stages](https://go-vela.github.io/docs/reference/yaml/stages/#tags), it looks like we just use `[]string` so I'll just document it like that for now. Happy to be wrong and change it if you'd like 😄

2021-07-30 16:21 UTC, wass3r approved these changes

2021-07-30 19:03 UTC, jbrockopp approved these changes
LGTM

2021-08-02 18:29 UTC, merged