chore: Add docs about ability to use templates in .vela.yml
go-vela/docs-old pull request #246
Opened 2021-09-02 16:22 UTC by JayCeeJr

Related Issue: https://git.cglcloud.com/DigitalFoundations-Enablement/enablement/issues/686

2021-09-07 17:04 UTC, JordanSussman requested changes
initial feedback

2021-09-07 17:04 UTC, JordanSussman commented on content/templates/_index.md
> +given you select the desired template language in the pipeline settings.
Can you add something about needing to do this within `https://vela.company.com/<org>/<repo>/settings`?

2021-09-07 17:04 UTC, JordanSussman commented on content/templates/_index.md
> +#### Example `.vela.yml` using Starlark
Thoughts on adding something about the ability to utilize [.vela.py and .vela.star](https://github.com/go-vela/server/blob/master/source/github/repo.go#L60-L62) instead of .vela.yml?

2021-09-07 17:04 UTC, JordanSussman commented on content/templates/_index.md
> +```yaml
Should utilize python to make syntax highlighting better.
```suggestion
```python
```

2021-09-08 15:06 UTC, matt-fevold approved these changes
LGTM

2021-09-08 18:57 UTC, wass3r approved these changes

2021-09-08 18:57 UTC, merged