chore(environment): adding documentation for the addition of a stage env
go-vela/docs-old pull request #265
Opened 2022-01-03 22:37 UTC by ecrupper

Adding some examples and further explanation of the environment now that it can be part of a stage. I also made the `Global Usage` section of the `Usage/Environment` page a bit more clear in the diff format

2022-02-08 16:21 UTC, jbrockopp requested changes

2022-02-08 16:21 UTC, jbrockopp commented on content/tour/environment.md
> +The global environment encompasses all stages and steps within the pipeline.
IIRC, the global environment also propagates to `services` too.

Do you think we should update this here to reflect that?

2022-02-08 19:35 UTC, jbrockopp approved these changes
LGTM

2022-02-09 19:23 UTC, wass3r approved these changes
thanks!

2022-02-09 20:50 UTC, merged