chore(api): add builds to get deployment
go-vela/docs-old pull request #267
Opened 2022-01-04 18:53 UTC by KellyMerrick

2022-01-04 22:36 UTC, wass3r requested changes
couple of tweaks and is the indentation off a bit? or is it just the preview?

2022-01-04 22:36 UTC, wass3r commented on content/reference/api/deployment/get.md
>      "description": "Deployment request from Vela"
```suggestion
    "description": "Deployment request from Vela",
```

2022-01-04 22:36 UTC, wass3r commented on content/reference/api/deployment/get.md
>      "description": "Deployment request from Vela"
```suggestion
    "description": "Deployment request from Vela",
```

2022-01-05 16:50 UTC, wass3r submitted a review, later dismissed

2022-01-07 16:35 UTC, jbrockopp requested changes

2022-01-07 16:35 UTC, jbrockopp commented on content/reference/api/deployment/get.md
> +    "id": 9,
Could you share why this line was changed?

Perhaps it was an accident? 😅 🤷

The reason I ask is because the `url` below still references deployment `1`.

2022-01-17 17:11 UTC, KellyMerrick commented on content/reference/api/deployment/get.md
> +    "id": 9,
I was attempting to demonstrate the relationship between builds and deployments, and missed updating the url. Should be fixed now.

2022-01-18 13:34 UTC, jbrockopp approved these changes
LGTM

2022-01-18 16:20 UTC, dtanner approved these changes

2022-01-18 20:06 UTC, merged