chore(usage): add secrets section for secrets concepts overview
go-vela/docs-old pull request #269
Opened 2022-01-11 15:08 UTC by KellyMerrick

2022-01-11 15:17 UTC, GregoryDosh commented on content/tour/secrets.md
> +Let's go back to our Docker image used within the plugin tutorial and focus only on the repository secrets type. You can learn about all secret types in the [secrets usage ssection](/docs/usage/secre
Small type here with `ssection`

2022-01-11 15:18 UTC, GregoryDosh commented on content/tour/secrets.md
> +Let's go back to our Docker image used within the plugin tutorial and focus only on the repository secrets type. You can learn about all secret types in the [secrets usage ssection](/docs/usage/secre
Irony in that I mistyped typo.

2022-01-17 16:36 UTC, kneal requested changes, later dismissed

2022-01-17 16:36 UTC, kneal commented on content/usage/secrets.md
> +
Extra space here I think

2022-01-17 16:36 UTC, kneal commented on content/usage/secrets.md
> +
Extra space here I think

2022-01-17 16:36 UTC, kneal commented on content/usage/secrets.md
> +
Extra space here I think

2022-01-17 16:36 UTC, kneal commented on content/usage/secrets.md
> +
Extra space here I think

2022-01-17 16:36 UTC, kneal commented on content/usage/secrets.md
> +
Extra space here I think

2022-01-17 16:36 UTC, kneal commented on content/usage/secrets.md
> +
Extra space here I think

2022-01-17 16:57 UTC, KellyMerrick commented on content/tour/secrets.md
> +Let's go back to our Docker image used within the plugin tutorial and focus only on the repository secrets type. You can learn about all secret types in the [secrets usage ssection](/docs/usage/secre
Fixed.

2022-01-17 16:57 UTC, KellyMerrick commented on content/usage/secrets.md
> +
Fixed.

2022-01-17 16:57 UTC, KellyMerrick commented on content/usage/secrets.md
> +
Fixed.

2022-01-17 16:58 UTC, KellyMerrick commented on content/usage/secrets.md
> +
Fixed.

2022-01-17 16:58 UTC, KellyMerrick commented on content/usage/secrets.md
> +
Fixed.

2022-01-17 16:58 UTC, KellyMerrick commented on content/usage/secrets.md
> +
Fixed.

2022-01-17 16:58 UTC, KellyMerrick commented on content/usage/secrets.md
> +
Fixed.

2022-01-19 17:10 UTC, jbrockopp commented on content/tour/secrets.md
> +Let's go back to our Docker image used within the plugin tutorial and focus only on the repository secrets type. You can learn about all secret types in the [secrets usage section](/docs/usage/secret
Should this say `repo` instead of `repository`?

```suggestion
Let's go back to our Docker image used within the plugin tutorial and focus only on the `repo` secrets type. You can learn about all secret types in the [secrets usage section](/docs/usage/secrets/).
```

I ask because I could go either way but in the codebase, we use `repo` as the type:

https://github.com/go-vela/types/blob/master/constants/secret.go#L12-L13

2022-01-19 17:10 UTC, jbrockopp commented on content/usage/examples/secrets_internal.md
> +The examples show a pipeline using repository secrets. Vela contains three secret types: repository, organization, and shared. Please see the [secret concepts](/docs/tour/secrets/) documentation.
Should this say `repo` instead of `repository` and `org` instead of `organization`?

```suggestion
The examples show a pipeline using repository secrets. Vela contains three secret types: `repo`, `org`, and `shared`. Please see the [secret concepts](/docs/tour/secrets/) documentation.
```

I ask because I could go either way but in the codebase, we use `repo` and `org` as the types:

https://github.com/go-vela/types/blob/master/constants/secret.go#L9-L13

2022-01-19 19:26 UTC, KellyMerrick commented on content/tour/secrets.md
> +Let's go back to our Docker image used within the plugin tutorial and focus only on the repository secrets type. You can learn about all secret types in the [secrets usage section](/docs/usage/secret
Consistency is good. Modified.

2022-01-19 19:26 UTC, KellyMerrick commented on content/usage/examples/secrets_internal.md
> +The examples show a pipeline using repository secrets. Vela contains three secret types: repository, organization, and shared. Please see the [secret concepts](/docs/tour/secrets/) documentation.
Consistency is good. Modified.

2022-01-19 21:39 UTC, wass3r commented on content/usage/secrets.md
> +Organization secrets are scoped to any repository in the organization. In order to create/modify these secrets you must be an organization admin.
should we call out that you have you be an org admin within the SCM?

2022-01-19 21:39 UTC, wass3r commented on content/usage/secrets.md
> +Shared secrets are scoped to any repository in the source control provider. Shared secrets are unique in the case they require a team to exist in your org. In order to create/modify these secrets you
Should we call out that the that the team and org lives within the SCM here as well, though it might get a bit weird because i'm not sure how "team" specifically fits with SCMs other than GitHub at the moment but maybe that's a battle for another day.

2022-01-20 14:13 UTC, GregoryDosh commented
Something else I had mentioned before and I don't know quite where it all fits (probably UI & Docs both) is the fact that anyone with write access to a repo in the SCM can potentially expose secrets, and then the fact that currently anyone who submits a PR can dump secrets if they're enabled for pull request events. I'm not saying this info has to be put here, but since we're talking about secrets sections and concepts and overviews I figured you'd have a good idea of where it might go.

2022-02-08 16:38 UTC, jbrockopp submitted a review, later dismissed
LGTM

2022-02-24 19:20 UTC, wass3r commented
checking in.. i like @GregoryDosh's point about adding something about secrets and PRs. I had a couple of more minor things called out to consider calling out the SCM for access control.

2022-03-01 17:51 UTC, KellyMerrick commented on content/usage/secrets.md
> +Shared secrets are scoped to any repository in the source control provider. Shared secrets are unique in the case they require a team to exist in your org. In order to create/modify these secrets you
Added a clarifier.

2022-03-01 17:51 UTC, KellyMerrick commented on content/usage/secrets.md
> +Organization secrets are scoped to any repository in the organization. In order to create/modify these secrets you must be an organization admin.
Added a clarifier.

2022-03-07 22:24 UTC, wass3r approved these changes

2022-03-08 02:30 UTC, JordanSussman approved these changes

2022-03-08 14:05 UTC, jbrockopp approved these changes
LGTM

2022-03-08 15:07 UTC, merged