chore(CLI): add documentation for CLI repo awareness
go-vela/docs-old pull request #272
Opened 2022-01-20 22:00 UTC by ecrupper

Decided to offer both cwd commands and targeted commands for each CLI command that includes the `--org` and `--repo` flags. Also elaborated on it a bit more in the config section.

2022-01-21 17:11 UTC, wass3r commented
Let's make this a draft so it doesn't get merged prematurely since this is not avail until the next release.

2022-02-08 17:03 UTC, jbrockopp requested changes

2022-02-08 17:03 UTC, jbrockopp commented on content/reference/cli/build/cancel.md
> +<div class="highlight"><pre><code><b>~/github/octocat $</b> vela cancel build --build 1</code></pre></div>
What if you instead used `pwd` in the output along with the `vela` CLI command?

i.e.

```sh
$ pwd
~/github/octocat
$ vela cancel build --build 1
```

My primary concern with this formatting is it could be confusing for users.

Especially, if that user is someone who doesn't have a ton of experience with terminals and CLIs.

To me, it's not very apparent what exactly is taking place here.

Also, I'm not a fan of HTML in documentation unless absolutely necessary.

2022-02-08 18:07 UTC, ecrupper commented on content/reference/cli/build/cancel.md
> +<div class="highlight"><pre><code><b>~/github/octocat $</b> vela cancel build --build 1</code></pre></div>
Sounds good. Changes made.

2022-02-08 20:19 UTC, jbrockopp approved these changes
LGTM

2022-02-09 19:17 UTC, wass3r approved these changes

2022-02-09 19:48 UTC, merged