feat: add FAQ section
go-vela/docs-old pull request #273
Opened 2022-01-24 21:52 UTC by jbrockopp

2022-02-01 22:13 UTC, JordanSussman approved these changes, later dismissed

2022-02-02 04:55 UTC, wass3r requested changes
thanks - love the addition. one change i would propose. i'm always hesitant for including screenshots as well. case in point, they are already outdated (albeit not majorly different at this point). not a request for changing it, more of a general statement.

2022-02-02 04:55 UTC, wass3r commented on content/faq/usage/_index.md
> +{{% /alert %}}
I think this should be taken out. It's making some assumptions about the flexibility of an installation.

2022-02-07 16:13 UTC, jbrockopp commented
@JordanSussman @wass3r this should be RFR 👍

2022-02-07 16:13 UTC, jbrockopp commented on content/faq/usage/_index.md
> +{{% /alert %}}
this is fixed 👍

2022-02-07 17:01 UTC, wass3r approved these changes
thanks!

2022-02-07 18:22 UTC, JordanSussman approved these changes

2022-02-07 22:32 UTC, merged