chore(guidelines): add communityy (intentional misspell) section with initial content
go-vela/docs-old pull request #281
Opened 2022-02-11 15:12 UTC by KellyMerrick

The intentional misspell for the `communityy` directory is to prevent the docsy theme's community page template from rendering, without having to modify the theme itself to prevent.

While it is a nice feature, our initial overview page has similar enough content, and this new section will render at the top and have similar styling as the other sections. We can easily add to this section as the project matures.

![image](https://user-images.githubusercontent.com/31659837/153616449-e77ac9f1-14ff-4af1-9b12-a34435db5417.png)

2022-02-15 15:43 UTC, kaymckay approved these changes, later dismissed
👍

2022-02-15 17:31 UTC, wass3r commented on content/community/contributing_guidelines/_index.md
> +- **Accessibility**  Coming soon.
How about:

> Vela strives to conform to [Web Content Accessibility Guidelines 2.1](https://www.w3.org/TR/WCAG21/) (AA) standards for accessibility. Please ensure your contribution(s) meets or exceeds this standard.

There are quite a few technical standards included in the referenced documentation. I don't think it makes sense to enumerate them here - the link probably suffices.

2022-02-15 18:41 UTC, kaymckay commented on content/community/contributing_guidelines/_index.md
> +- **Accessibility**  Coming soon.
Sounds good to me 👍

2022-02-15 18:43 UTC, plyr4 requested changes, later dismissed

2022-02-15 18:43 UTC, plyr4 commented on content/community/contributing_guidelines/_index.md
> +Make sure an issue](https://github.com/go-vela/community/issues) or [proposal](https://github.com/go-vela/community/tree/master/proposals) in the [go-vela/community](https://github.com/go-vela/commun
typo, no opening `[` bracket 
```suggestion
Make sure an [issue](https://github.com/go-vela/community/issues) or [proposal](https://github.com/go-vela/community/tree/master/proposals) in the [go-vela/community](https://github.com/go-vela/community) repository exists prior to beginning any code changes.
```

2022-02-15 18:43 UTC, plyr4 commented on content/community/contributing_guidelines/_index.md
> +Before contributing any code, make sure an issue](/docs/communityy/contributing_guidelines/#issues) exists, be sure to checkout current issues](https://github.com/go-vela/community/issues) and [propo
typo, no opening `[` bracket
```suggestion
Before contributing any code, make sure an [issue](/docs/communityy/contributing_guidelines/#issues) exists, be sure to checkout current issues](https://github.com/go-vela/community/issues) and [proposals](https://github.com/go-vela/community/tree/master/proposals) to make sure your idea isn’t already being worked on. We're working on a public roadmap view to link here.
```

2022-02-15 18:43 UTC, plyr4 commented on content/community/contributing_guidelines/_index.md
> +If there isn’t an issue, make sure to create one.
just being picky
```suggestion
If an issue does not exist, make sure to create one.
```

2022-02-15 18:43 UTC, plyr4 commented on content/community/contributing_guidelines/_index.md
> +Vela is Target’s primary CI system. We will evaluate issues and proposals against our roadmap, what is best for Target, and makes sense to implement for other customers that will provide a general po
```suggestion
Vela is Target’s primary CI system. We will evaluate issues and proposals and compare them against our roadmap, what is best for Target, and what makes sense to implement that will provide general positive value for other users.
```

2022-02-15 18:43 UTC, plyr4 commented on content/community/contributing_guidelines/_index.md
> +See [style guide](/docs/communityy/contributing_guidelines/#style-guide) for guides on implementation.
typo
```suggestion
See [style guide](/docs/community/contributing_guidelines/#style-guide) for guides on implementation.
```

2022-02-15 18:43 UTC, plyr4 commented on content/community/contributing_guidelines/_index.md
> +### Backlog grooming
picky, feel free to ignore
```suggestion
### Backlog Grooming
```

2022-02-15 18:43 UTC, plyr4 commented on content/community/contributing_guidelines/_index.md
> +  * For the title of the pull request, please use the following format for the title:
```suggestion
  * For the title of the pull request, please use the following format:
```

2022-02-15 18:43 UTC, plyr4 commented on content/community/contributing_guidelines/_index.md
> +Currently, main releases only apply to [core repos](/docs/communityy/contributing_guidelines/#core-repos). [Plugin repos](/docs/communityy/contributing_guidelines/#plugin-repos) get version cuts on a
```suggestion
Currently, main releases only apply to [core repos](/docs/community/contributing_guidelines/#core-repos). [Plugin repos](/docs/community/contributing_guidelines/#plugin-repos) get version cuts on an as needed basis.
```

2022-02-16 02:08 UTC, KellyMerrick commented
Feedback implemented.

2022-02-16 19:01 UTC, kaymckay submitted a review, later dismissed

2022-02-16 19:01 UTC, kaymckay commented on content/community/contributing_guidelines/_index.md
> +Create a pull request using the [proposal template](link to proposals readme).
missing link : https://github.com/go-vela/community/blob/master/.github/PULL_REQUEST_TEMPLATE/proposal.md

2022-02-16 19:01 UTC, kaymckay commented on content/community/contributing_guidelines/_index.md
> +  * Getting Approved: For [core repos](), PRs need 2 approvals. At least one approval must come from an admin, the other can be from a trusted committer. For plugin repos, 1 approval from an admin or
missing core repo reference (/docs/community/contributing_guidelines/#core-repos)

2022-02-16 19:01 UTC, kaymckay commented on content/community/contributing_guidelines/_index.md
> +- **Dependency management:** Check out the [core repos](#dependency-tree-for-core-repos) and the [plugin repos](/docs/community/contributing_guidelines/#plugin-repos) to see how they are dependent on
is there a difference between (#dependency-tree-for-core-repos) and using the full path (/docs/community/contributing_guidelines/#plugin-repos) for indoc linking?

2022-02-18 15:17 UTC, KellyMerrick commented on content/community/contributing_guidelines/_index.md
> +- **Dependency management:** Check out the [core repos](#dependency-tree-for-core-repos) and the [plugin repos](/docs/community/contributing_guidelines/#plugin-repos) to see how they are dependent on
missed updating the the dependency tree link, and added a clarifier for plugins regarding dependencies.

2022-02-18 15:17 UTC, KellyMerrick commented on content/community/contributing_guidelines/_index.md
> +Create a pull request using the [proposal template](link to proposals readme).
fixed

2022-02-18 15:18 UTC, KellyMerrick commented on content/community/contributing_guidelines/_index.md
> +  * Getting Approved: For [core repos](), PRs need 2 approvals. At least one approval must come from an admin, the other can be from a trusted committer. For plugin repos, 1 approval from an admin or
fixed

2022-02-18 15:27 UTC, JordanSussman reviewed
minor comments

2022-02-18 15:27 UTC, JordanSussman commented on content/community/contributing_guidelines/_index.md
> +Vela is Target’s primary CI system. We will evaluate issues and proposals, and compare them against our roadmap, what is best for Target, and what makes sense to implement for other customers that wi
Any objections to changing customers to installations or companies? The wording of customers can be confusing since it isn't clear if you are referencing internal vs external.

2022-02-18 15:27 UTC, JordanSussman commented on content/community/contributing_guidelines/_index.md
> +Our [project boards](https://github.com/orgs/go-vela/projects) give you a detailed overview of what’s currently planned or being worked on. Each sprint reflects the stage in our roadmap we are focuse
Should the length of the typically sprint be defined somewhere? e.g. the Target team typically aims to tie the sprint duration to the monthly release cycle.

2022-02-18 18:50 UTC, KellyMerrick commented on content/community/contributing_guidelines/_index.md
> +Vela is Target’s primary CI system. We will evaluate issues and proposals, and compare them against our roadmap, what is best for Target, and what makes sense to implement for other customers that wi
I like it. Changing.

2022-02-18 19:01 UTC, KellyMerrick commented on content/community/contributing_guidelines/_index.md
> +Our [project boards](https://github.com/orgs/go-vela/projects) give you a detailed overview of what’s currently planned or being worked on. Each sprint reflects the stage in our roadmap we are focuse
Good call. Added.

2022-02-21 21:08 UTC, kaymckay commented on content/community/contributing_guidelines/_index.md
> +Before contributing any code, make sure an [issue](/docs/community/contributing_guidelines/#issues) exists, be sure to checkout current issues](https://github.com/go-vela/community/issues) and [propo
missing [ on second issue

2022-03-01 16:17 UTC, KellyMerrick commented on content/community/contributing_guidelines/_index.md
> +Before contributing any code, make sure an [issue](/docs/community/contributing_guidelines/#issues) exists, be sure to checkout current issues](https://github.com/go-vela/community/issues) and [propo
Fixed.

2022-03-01 16:30 UTC, kaymckay commented on content/community/contributing_guidelines/_index.md
> +Before contributing any code, make sure an [issue](/docs/community/contributing_guidelines/#issues) exists, be sure to checkout current issues](https://github.com/go-vela/community/issues) and [propo
It's not showing fixed in the PR

2022-03-01 19:37 UTC, kaymckay approved these changes

2022-03-03 15:40 UTC, plyr4 approved these changes
LGTM ty for the updates!

2022-03-03 16:11 UTC, merged