feat: add docs for new render inline option
go-vela/docs-old pull request #291
Opened 2022-03-17 20:23 UTC by kneal

2022-03-25 14:33 UTC, wass3r requested changes

2022-03-25 14:33 UTC, wass3r commented on content/reference/yaml/metadata.md
> +| `render_inline` | N        | bool | Enables rendering for templates without stages/steps.  |
i don't think this description is quite accurate? you can have either as long as the template has the same (ie. template injects stages, your base pipeline needs to have stages too). in fact, should that factoid be called out somewhere?

2022-03-25 17:14 UTC, kneal commented on content/reference/yaml/metadata.md
> +| `render_inline` | N        | bool | Enables rendering for templates without stages/steps.  |
Yeah, that's what it can do but probably not phrased in the correct spot. It's weird because the work was done in the story to enable Stages for templates but the feature does that indirectly by unlocking many more features.

2022-04-05 00:11 UTC, wass3r commented on content/reference/yaml/metadata.md
> +| `render_inline` | N        | bool | Enables rendering for templates without stages/steps.  |
I guess we'll merge as is and amend after.

2022-04-05 00:12 UTC, wass3r submitted a review, later dismissed

2022-04-05 18:58 UTC, kneal commented on content/reference/yaml/metadata.md
> +| `render_inline` | N        | bool | Enables rendering for templates without stages/steps.  |
> (ie. template injects stages, your base pipeline needs to have stages too)

The examples provided in the other file are stages injections. I would hope that would be intuitive enough to show that stages can be templated but I suppose we could be more specific.

2022-04-05 20:15 UTC, cognifloyd approved these changes
Ooh. This looks like a sweet feature!

2022-04-05 22:17 UTC, wass3r approved these changes
thanks!

2022-04-05 22:17 UTC, merged