fix: broken links and clarify check-in
go-vela/docs-old pull request #323
Opened 2022-09-14 05:08 UTC by wass3r

fixing a few broken links.

the TODO didn't have a valid target page, so I took some liberties to rework it. i cross-referenced the check-durations on the server and worker since there should be some coordination there so you get somewhat accurate values. 

while doing so, i realized the defaults might need updating in code to match better? with the current defaults, it's quite possible your active worker count is off.

2022-09-14 15:28 UTC, jbrockopp requested changes

2022-09-14 15:28 UTC, jbrockopp commented on content/installation/server/reference/_index.md
> +setting provided to the [worker](/docs/installation/worker/)
I think we want to condense this into one line and missing `.`:

```suggestion
The value should coordinate with the [`VELA_CHECK_IN`](/docs/installation/worker/reference/#vela_check_in) setting provided to the [worker](/docs/installation/worker/).
```

2022-09-14 15:28 UTC, jbrockopp commented on content/installation/worker/reference/_index.md
> +setting provided to the [server](/docs/installation/server/)
one line and missing `.`:

```suggestion
The value should coordinate with the [`VELA_WORKER_ACTIVE_INTERVAL`](/docs/installation/server/reference/#vela_worker_active_interval) setting provided to the [server](/docs/installation/server/).
```

2022-09-14 15:53 UTC, wass3r commented
changes made - thanks @jbrockopp

2022-09-14 15:57 UTC, jbrockopp approved these changes
LGTM

2022-09-16 19:03 UTC, plyr4 approved these changes

2022-09-16 19:17 UTC, merged