chore(stages): add orchestration docs under usage section
go-vela/docs-old pull request #356
Opened 2023-04-11 18:55 UTC by ecrupper

I think it would be worth while to add more examples / explanations for the various orchestration tools given to users when it comes to `stages`, such as `needs` and `independent`. Further, I think outlining the behavior of stage pipelines in the context of ruleset pruning can be very helpful. 

Let me know if you think this content belongs elsewhere in the docs or if you have any edits / comments!

2023-04-11 22:03 UTC, wass3rw3rk approved these changes, later dismissed
minor nitpick, otherwise, nice job

2023-04-11 22:03 UTC, wass3rw3rk commented on content/usage/stage_orchestration.md
> +This page will focus on [`stages`](/docs/tour/stages) and how to effectively leverage the orchestration options given to users. These options come in the form of [`rulesets`](/docs/tour/rulesets), [`
nit pick: remove backticks around "independence" since it isn't an actual keyword in a pipeline like the other ones are. alternatively, change to `independent` (with backticks), but then the sentence reads funny.

```suggestion
This page will focus on [`stages`](/docs/tour/stages) and how to effectively leverage the orchestration options given to users. These options come in the form of [`rulesets`](/docs/tour/rulesets), [`needs`](/docs/reference/yaml/stages/#the-needs-tag), and [independence](/docs/reference/yaml/stages/#the-independent-tag).
```

2023-04-13 14:45 UTC, cognifloyd requested changes

2023-04-13 14:45 UTC, cognifloyd commented on content/usage/stage_orchestration.md
> +This page will focus on [`stages`](/docs/tour/stages) and how to effectively leverage the orchestration options given to users. These options come in the form of [`rulesets`](/docs/tour/rulesets), [`
```suggestion
This page will focus on [`stages`](/docs/tour/stages) and how to effectively leverage the orchestration options given to users. These options are: [`rulesets`](/docs/tour/rulesets), [`needs`](/docs/reference/yaml/stages/#the-needs-tag), and [`independent`](/docs/reference/yaml/stages/#the-independent-tag).
```

2023-04-13 14:45 UTC, cognifloyd commented on content/usage/stage_orchestration.md
> +To begin, let's focus on the `ruleset` tag. While this is not a tag at the stages level at the moment, each stage has a collection of steps, which can all be given rulesets. There are two kinds of ru
```suggestion
To begin, let's focus on the `ruleset` tag. While this is not a tag at the stages level, each stage has a collection of steps, which can all be given rulesets. There are two kinds of rules within Vela: compile-time rules (path, event, branch, comment, tag, target, and repo) and a runtime rule (status). When Vela compiles a pipeline, it will purge any steps that do not meet the compile-time rules.
```

2023-04-13 14:45 UTC, cognifloyd commented on content/usage/stage_orchestration.md
> +While there isn't a sure-fire way of running stages in order, there is the `needs` tag, which introduces a level of dependency that can be used to order stages. However, noting the example above, the
```suggestion
While there isn't a sure-fire way of running stages in order, the `needs` tag introduces a level of dependency that can be used to order stages. However, the `needs` tag can become tricky when combined with pruning, as shown in the example above. Let's take a look at another theoretical pipeline:
```

2023-04-13 14:45 UTC, cognifloyd commented on content/usage/stage_orchestration.md
> +So in fact, in this scenario, the `run-first` stage and the `y-stage` begin simultaneously, even though `y-stage` "needed" `compile-time-ruleset-stage` which "needed" `run-first` in the original pipe
Wow! Yes this needed to be documented. That is surprising.

2023-04-13 14:45 UTC, cognifloyd commented on content/usage/stage_orchestration.md
> +For example, say we have a repo that has back-end _and_ front-end code written together. Let's assume all the back-end code is in `org/repo/back-end` and the front-end code is in `org/repo/front-end`
```suggestion
For example, say we have a repo that has back-end _and_ front-end code written together. Let's assume all the back-end code is in `org/repo/back-end` and the front-end code is in `org/repo/front-end`. We can leverage the [`path`](/docs/reference/yaml/steps/#the-ruleset-tag) ruleset with the [`independent`](/docs/reference/yaml/stages/#the-independent-tag) stage tag to compartmentalize Vela builds:
```

2023-04-13 14:45 UTC, cognifloyd commented on content/usage/stage_orchestration.md
> +Stages are an advanced tool to help with writing powerful and sensible pipelines with parallel execution. While these orchestration tools are helpful, it is worth investigating just using `steps` if
```suggestion
Stages are an advanced tool to help with writing powerful and sensible pipelines with parallel execution. While these orchestration tools are helpful, consider just using `steps` to simplify pipelines that don't need the, sometimes surprising, complexity.
 
```

2023-04-13 15:23 UTC, ecrupper commented on content/usage/stage_orchestration.md
> +This page will focus on [`stages`](/docs/tour/stages) and how to effectively leverage the orchestration options given to users. These options come in the form of [`rulesets`](/docs/tour/rulesets), [`
Decided to be explicit with this one and keep all the refs exactly how they are as tags and call out specifically that they are tags. Thanks!

2023-04-13 15:33 UTC, cognifloyd commented on content/usage/stage_orchestration.md
> +Stages are an advanced tool to help with writing powerful and sensible pipelines with parallel execution. While these orchestration tools are helpful, consider just using `steps` to simplify pipeline
Single char nit: Needs a new line at the end of the file

2023-04-13 16:25 UTC, cognifloyd approved these changes

2023-04-13 16:38 UTC, timhuynh94 approved these changes

2023-04-13 16:39 UTC, merged