feat(worker): add worker commands
go-vela/docs-old pull request #362
Opened 2023-04-14 16:10 UTC by wass3rw3rk

2023-04-25 19:16 UTC, ecrupper requested changes
Nice — couple things I noticed

2023-04-25 19:16 UTC, ecrupper commented on content/reference/cli/worker/update.md
> +| `routes`          | route assignment for the worker  | `VELA_WORKER_ROUTES`, `WORKER_ROUTES`           |
I don't think it's possible to adjust the build limit via the API: https://github.com/go-vela/server/blob/7eda80aa14a51ef82dba73cda9f2556f48e346d7/api/worker.go#L311-L324. Also, even though it technically adjusts routes, we don't actually go in and change it on that worker, so I wonder if advertising it in the docs is kind of misleading?

2023-04-25 19:16 UTC, ecrupper commented on content/reference/cli/worker/update.md
> +$ vela update worker --worker.hostname MyWorker --worker.address newaddress.example.com
Should we advertise the new way of just using worker address?

2023-04-25 19:16 UTC, ecrupper commented on content/reference/cli/worker/view.md
> +| `worker.registration.token` | show the registration token for the worker (requires Vela Platform Admin) | `VELA_WORKER_REGISTRATION_TOKEN`, `WORKER_REGISTRATION_TOKEN` |
```suggestion
| `worker.registration.token` | generate a registration token for the worker (requires Vela Platform Admin) | `VELA_WORKER_REGISTRATION_TOKEN`, `WORKER_REGISTRATION_TOKEN` |
```

Maybe?

2023-04-25 21:28 UTC, wass3rw3rk commented on content/reference/cli/worker/update.md
> +$ vela update worker --worker.hostname MyWorker --worker.address newaddress.example.com
Good call

2023-04-25 21:29 UTC, wass3rw3rk commented on content/reference/cli/worker/view.md
> +| `worker.registration.token` | show the registration token for the worker (requires Vela Platform Admin) | `VELA_WORKER_REGISTRATION_TOKEN`, `WORKER_REGISTRATION_TOKEN` |
i'm cool with that

2023-04-25 21:30 UTC, wass3rw3rk commented on content/reference/cli/worker/update.md
> +| `routes`          | route assignment for the worker  | `VELA_WORKER_ROUTES`, `WORKER_ROUTES`           |
i meanm it does change the value, the value is just not being used. how about we mark those values as `(unused)`?

2023-04-25 21:31 UTC, wass3rw3rk commented on content/reference/cli/worker/update.md
> +| `routes`          | route assignment for the worker  | `VELA_WORKER_ROUTES`, `WORKER_ROUTES`           |
Oops, my bad. For that specific value, you are correct. Even for the other unused values, i think we want to mark them somehow.

2023-04-25 22:08 UTC, wass3rw3rk commented on content/reference/cli/worker/update.md
> +| `routes`          | route assignment for the worker  | `VELA_WORKER_ROUTES`, `WORKER_ROUTES`           |
addressed

2023-04-25 22:08 UTC, wass3rw3rk commented on content/reference/cli/worker/update.md
> +$ vela update worker --worker.hostname MyWorker --worker.address newaddress.example.com
addressed

2023-04-25 22:11 UTC, plyr4 commented on content/reference/cli/worker/add.md
> +$ vela add worker --worker.hostname MyWorker --worker.address myworker.example.com
minor, should we include protocol? 
```suggestion
$ vela add worker --worker.hostname MyWorker --worker.address https://myworker.example.com
```

2023-04-25 22:12 UTC, plyr4 commented on content/reference/cli/worker/add.md
> +$ vela add worker --worker.hostname MyWorker --worker.address myworker.example.com
meh, not necessary, that should be inferred

2023-04-25 22:14 UTC, ecrupper approved these changes

2023-04-25 22:14 UTC, plyr4 approved these changes

2023-04-26 13:38 UTC, timhuynh94 approved these changes

2023-04-26 13:49 UTC, merged