feat: adding deploy_number environment variable to docs
go-vela/docs-old pull request #395
Opened 2024-02-08 19:38 UTC by claire1618

Adding the new deploy_number environment variable present during deployments to the docs.

2024-02-08 19:44 UTC, timhuynh94 approved these changes

2024-02-09 17:37 UTC, wass3rw3rk requested changes

2024-02-09 17:37 UTC, wass3rw3rk commented on content/reference/environment/variables.md
> +| `VELA_DEPLOYMENT_NUMBER`   | `production` | number of deployment from GitHub              |
i think value is not correct for `VELA_DEPLOYMENT_NUMBER`

2024-02-12 21:37 UTC, wass3rw3rk commented on content/reference/environment/variables.md
> +| `VELA_DEPLOYMENT_NUMBER`   | `production` | number of deployment from GitHub              |
addressed in https://github.com/go-vela/docs/pull/393

2024-02-12 21:38 UTC, wass3rw3rk commented
changes were included in https://github.com/go-vela/docs/pull/393

2024-02-12 21:38 UTC, closed without merging